### ISSUE TITLE
Add support Azure Storage Queue

### ISSUE THREAD

**Issue by developerxnz** [Azure/azure-k8s-metrics-adapter#39]
Add support to access Storage Queue Message Count using the [azure go sdk](https://github.com/Azure/azure-sdk-for-go).

**Comment by tomkerkhove** [comment]
This is actually already supported - https://github.com/Azure/azure-k8s-metrics-adapter#external-metrics.

Every metric that is available in Azure Monitor, is waiting for you to use!

**Comment by jsturtevant** [comment]
I thought the same initially but I have found that there are edge cases on how each metric is reported to Azure Monitor.  In this case, Azure Storage [only reports the queue Capacity Metrics every 24 hours](https://docs.microsoft.com/en-us/azure/storage/common/storage-metrics-in-azure-monitor?toc=%2fazure%2fstorage%2fqueues%2ftoc.json#capacity-metrics).  I tested this to confirm it and found that for the first day I did not get any Queue message counts,  The second day I had the counts.  

This makes the Azure Monitor metric not very useful in this use case. In addition, the metric reported to Azure Monitor by Azure Storage Queue's is total messages across all queues and [doesn't currently support dimensions for per queue metrics](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics#microsoftstoragestorageaccountsqueueservices).

To enable this will need to create a way to use a different api endpoint via the go SDK.  It does look like we can get the [QueueMessage Count through the SDK](https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Queue).   

I am currently thinking we modify the [ExternalMetric CRD](https://github.com/Azure/azure-k8s-metrics-adapter/blob/master/samples/resources/externalmetric-example.yaml) to have a type that can override the type of api endpoint we want to query.  This way we could have an ExternalMetric that uses Azure Monitor, Storage Queue, or any other one that comes up with a limitation like this.

**Comment by tomkerkhove** [comment]
Too bad but makes sense to me! Will the schema be different based on that type? Otherwise, would it make sense to create a new CRD instead?

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by jsturtevant** [comment]
I am planning on re-using the same ExternalMetric CRD with a property that will tell us the type and use a different schema based on each type. I think having too many CRD types will get confusing and is harder to maintain in the code. It would look something like:

```
apiVersion: azure.com/v1alpha2
kind: ExternalMetric
metadata:
  name: example-external-metric-sb
spec:
  type: azuremonitor
  config:
    azure:
      resourceGroup: sb-external-example
      resourceName: sb-external-ns
      resourceProviderNamespace: Microsoft.ServiceBus
      resourceType: namespaces
    metric:
      metricName: Messages
      aggregation: Total
      filter: EntityName eq 'externalq'
```

or 

```
apiVersion: azure.com/v1alpha2
kind: ExternalMetric
metadata:
  name: example-external-metric-sb
spec:
  type: storagequeue
  config:
    queuename: test1
    resourcegroup: storage-rg
```

I am not sure what config is nessary for the storage queue example currently but that give you a sense of what I am thinking.
