### ISSUE TITLE
Error: deployment of azureexternalmetric instead of actual deployments

### ISSUE THREAD

**Issue by srsrin** [Azure/azure-k8s-metrics-adapter#53]
**Describe the bug**
We are attempting to use horizontal pod autoscaling in our cluster. The cluster autoscaler yaml is already deployed to our cluster but not through helm. However the HorizontalPodAutoscaler yamls are in our charts folder and are deployed through helm in the same namespace that the normal deployments should be in. In addition, i have just deployed azure metrics adapter by cloning the repo and running helm upgrade on it. However, what seems to be happening is instead of the deployments getting pushed to the cluster, the azure metrics adapter pushes its own deployment with the name of namespace im trying to push all the deployments to. And then I dont see my deployments pushed. 

**To Reproduce**
Have a cluster that has the clusterautoscaler
run helm upgrade charts/azure-k8s-metrics-adapter which proper values for auth etc in namespace custom-metrics
run helm upgrade charts/<cluster-deployments-and-hpas> which have yamls for deployments and hpa's that link to those specific deployments in namespace <namespace>

**Expected behavior**
using the aem, the hpas should connect to the deployments and they should deploy. instead, the azure-k8s-adapter deploys its own deployment.

One attempt at fixing this was to remove the deployment.yaml file from the charts/azure-k8s-metrics-adapter repo however, that made it so that i got the error: "deployments/scale.extensions not found" 

This whole process was in an attempt to use helm to deploy the aem. Previously the yaml for the aem was generated through the command line using `helm install charts/azure-k8s-metric-adapter` with appropriate tags necessary.

This produced:
![image](https://user-images.githubusercontent.com/45807532/50174769-ea99ef80-02af-11e9-9b45-615cea3c4271.png)
However, this is an attempt to generate the appropriate yaml through charts in a CI/CD pipeline. When done this way, there doesn't seem to be the custom-role-bindings:
![image](https://user-images.githubusercontent.com/45807532/50174967-7b70cb00-02b0-11e9-93f5-48c8284bf47d.png)

I have doublechecked that all tags are the same and auth is the same. 
 

**Kubernetes version (`kubectl version`):**
- [ ] 1.10+

**Logs (`kubectl logs <metric adapter pod id>`)**

**Additional context**
Add any other context about the problem here. (HPA, Custom/External Metric CRD, azure auth type, etc.)

**Comment by srsrin** [comment]
Also, once the azure metrics adapter is installed in the cluster, theoretically, running `kubectl get aem -n ping` should get the external metrics. However, im getting an error: "the server doesn't have a resource type "aem" " even though the charts should generate a shorthand for the azure external metric as aem. This makes me think the aem ins't getting deployed properly. Thank you for your help in this matter

**Comment by srsrin** [comment]
I can also see the customresourcedefinitions: 
![image](https://user-images.githubusercontent.com/45807532/50178122-86c7f480-02b8-11e9-9d16-916708482b51.png)

**Comment by jsturtevant** [comment]
It looks like there a few different things happening.  First, if you deployed something manually via a yaml file, then you can't use helm to manage it because helm doesn't know about the deployment, so `helm upgrade` won't behave like you expect.  I think that might be the source of some of the issues.  Currently, it is not possible to run [multiple versions of a custom metric adapter](https://github.com/kubernetes-incubator/custom-metrics-apiserver/issues/3).  I would recommend removing your initial yaml file deployment (kubectl delete -f <file>) and deploy only with helm if that's the deployment method you choose.

For getting all the external metrics via `kubectl get aem -n ping`, are the metrics stored in the namespace `ping`?  What happens if you do `kubectl get aem --all-namespaces`?  I have see the shortcut take some time to load, for instance I ran `kubectl get aem` directly after a deployment and it returned nothing then a few minutes later I was able to run the same command (not sure what causes this but seem related to the way CRD's are loaded into the system).  Does `kubectl get externalmetric` work?

For using --raw to query endpoints,  `kubectl get --raw "/apis/metrics.k8s.io/v1beta/nodes` will return the node cpu and memory.  This isn't related to the metric adapter but is the default values for the metric server.  You will need to make sure your user has permissions for that endpoint.  The endpoint that is registered for the adapter is `kubectl  get --raw "/apis/external.metrics.k8s.io/v1beta1/`

**Comment by srsrin** [comment]
Ok, yes I agree because the adapter.yaml and the clusterautoscaler.yaml were manually deployed to the cluster pre-helm, the helm upgrade step isnt working. 

Say we have a new cluster that isn't muddled with attempts to helm the autoscaler as well as the adapter, could you provide a walkthrough of how to properly deploy the elements. Specifically, our pipeline on VSTS/Azure DevOps uses helm to deploy deployments to a namespace'ping'. However, in this same pipeline I would like to first 'helm upgrade' the cluster autoscaler and the adapter in the custom-metrics namespace. 

To answer your questions:
1. there are external metrics for ping. Before attempting to helm `kubectl get aem -n ping' would return the external metrics information correctly. i will try accessing the endpoints. 

Thank you for your involved help. It is greatly appreciated

**Comment by srsrin** [comment]
We will be using the client secret method for authentication however i dont want to include the client id and secret during the release, rather I would like to have the secret exist in the cluster and it would link to the name of the service principal. is there a way to do that with helm as a part of release pipeline as mentioned above. 

LMK if you have any questions!

Thanks!

**Comment by jsturtevant** [comment]
By default the Helm chart does not install secrets.  If you set the `azureAuthentication.method=clientSecret` and don't provide the the clientid/etc, your deployment will look like (note the env variables section):

```yaml
$ helm install -n dryruntest --debug --dry-run --set azureAuthentication.method=clientSecret ./azure-k8s-metrics-adapter

#truncated output for brevity....

# Source: azure-k8s-metrics-adapter/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dryruntest-azure-k8s-metrics-adapter
  namespace: "default"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: dryruntest
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-k8s-metrics-adapter
      release: dryruntest
  template:
    metadata:
      labels:
        app: azure-k8s-metrics-adapter
        release: dryruntest
    spec:
      serviceAccountName: dryruntest-azure-k8s-metrics-adapter
      containers:
        - name: azure-k8s-metrics-adapter
          image: "mcr.microsoft.com/k8s/metrics/adapter:latest"
          imagePullPolicy: Always
          args:
            - /adapter
            - --secure-port=6443
            - --logtostderr=true
            - --v=2
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: dryruntest-azure-k8s-metrics-adapter
                  key: azure-tenant-id
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dryruntest-azure-k8s-metrics-adapter
                  key: azure-client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dryruntest-azure-k8s-metrics-adapter
                  key: azure-client-secret
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
          resources:
            {}

      volumes:
        - name: temp-vol
          emptyDir: {}
```

and then you can create a secret with the name specified above: `dryruntest-azure-k8s-metrics-adapter` with the keys `azure-client-secret` and `azure-tenant-id` and `azure-client-id`.  

The secret name is the name of your `helm release name` + `azure-k8s-metric-adapter`.  So in this case the secret name is `dryruntest-azure-k8s-metrics-adapter` but will be different in your specific deployment.
