### ISSUE TITLE
FailedComputeMetricsReplicas... unable to fetch metrics from external metrics API: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token...

### ISSUE THREAD

**Issue by eugen-nw** [Azure/azure-k8s-metrics-adapter#54]
Could someone please help me to do what is needed in order to get the Message Queue size auto-scaling working?

The complete error I'm seeing is below.  The expected result would (probably) be to get a 0 value back since there's no message in the queue at this time.
```
kubectl  get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/queuemessages"
Error from server (BadRequest): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com//subscriptions/d1151462-af84-4066-8ebc-62a4191a356e/resourceGroups/Eugen-Prototypes/providers/Microsoft.ServiceBus/namespaces/eugenservicebus/providers/microsoft.insights/metrics?%24filter=EntityName+eq+%27requestqueue%27&aggregation=Total&api-version=2018-01-01&metricnames=Messages&timespan=2019-01-04T19%3A20%3A10Z%2F2019-01-04T19%3A25%3A10Z: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```
#### Starting point
I'm using an Azure Kubernetes Service instance, 'kubectl version' returns:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
The Metrics Server was already present in the AKS instance:
```
kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"
{"kind":"NodeMetricsList","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/metrics.k8s.io/v1beta1/nodes"},"items":[{"metadata":{"name":"aks-agentpool-42482945-0","selfLink":"/apis/metrics.k8s.io/v1beta1/nodes/aks-agentpool-42482945-0","creationTimestamp":"2019-01-04T19:46:48Z"},"timestamp":"2019-01-04T19:46:00Z","window":"1m0s","usage":{"cpu":"111m","memory":"1447864Ki"}}]}
```
#### To set up auto-scaling
Following the steps at https://www.jamessturtevant.com/posts/Azure-Kubernetes-Metric-Adapter/ I setup the Metrics Adapter using the command:
```
kubectl apply -f https://raw.githubusercontent.com/Azure/azure-k8s-metrics-adapter/master/deploy/adapter.yaml
``` 
In the last step of the setup I used HPA.yaml file below:
```apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: external-solver-runner-scaler
spec:
 scaleTargetRef:
   apiVersion: extensions/v1beta1
   kind: Deployment
   name: aks-aci-boldiq-external-solver-runner
 minReplicas: 1
 maxReplicas: 10
 metrics:
  - type: External
    external:
      metricName: queuemessages
      targetValue: 2
```
Following some of the steps at https://github.com/Azure/azure-k8s-metrics-adapter/tree/master/samples/servicebus-queue I set up:
```
az ad sp create-for-rbac -n "adapter-sp" --role "Monitoring Reader" --scopes /subscriptions/d1151462-af84-4066-8ebc-62a4191a356e/resourceGroups/Eugen-Prototypes
{
  "appId": "the_app_id",
  "displayName": "adapter-sp",
  "name": "http://adapter-sp",
  "password": "the_password",
  "tenant": "the_tenant"
}

kubectl create secret generic adapter-service-principal -n custom-metrics --from-literal=azure-tenant-id=the_tenant --from-literal=azure-client-id=the_app_id  --from-literal=azure-client-secret=the_password
```
And configured the External Metric:
```
apiVersion: azure.com/v1alpha1
kind: ExternalMetric
metadata:
  name: queuemessages
spec:
  azure:
    resourceGroup: Eugen-Prototypes
    resourceName: eugenservicebus
    resourceProviderNamespace: Microsoft.ServiceBus
    resourceType: namespaces
  metric:
    metricName: Messages
    aggregation: Total
    filter: EntityName eq 'requestqueue'
```

**Comment by jsturtevant** [comment]
It looks like the file located at  https://raw.githubusercontent.com/Azure/azure-k8s-metrics-adapter/master/deploy/adapter.yaml doesn't have the correct environment variables injected into the adapter deployment.  This is due to the way it is currently being auto-generated.  I will take a look at modifying as this is confusing for someone trying it the first time.  

For now you can download the deployment yaml and modify it to add the secret.  The deployment should look something like https://github.com/Azure/azure-k8s-metrics-adapter/blob/master/samples/azure-authentication/adapter-with-ad-sp.yaml.

The environment variable you need to inject into the deployment with the name of your secret you created (make sure the names line up) looks like:

```
        env:
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: adapter-service-principal
                key: azure-tenant-id
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: adapter-service-principal
                key: azure-client-id
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: adapter-service-principal
                key: azure-client-secret
```

**Comment by eugen-nw** [comment]
Thanks VERY MUCH James for your help!  It works now although I am not certain that I'm getting the right results:

`kubectl  get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/queuemessages"` returns:
```
{
	"kind": "ExternalMetricValueList",
	"apiVersion": "external.metrics.k8s.io/v1beta1",
	"metadata": {
		"selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/queuemessages"
	},
	"items": [{
			"metricName": "queuemessages",
			"metricLabels": null,
			"timestamp": "2019-01-07T20:58:43Z",
			"value": "10"
		}
	]
}
```

It looks suspicious to me that am I seeing a value of 10 because the Queue in question is empty and there isn't anyone sending/receiving messages.  I would expect to see a value of 0.  What's even more interesting is that successive calls return either 9 or 10.  Are we looking at the wrong Queue metric by any chance?

For the record, this is step-by-step what I did (in addition to creating the Service Principal and the K8s secret):
1. I removed all 3 .yaml based configurations I previously did.
2. I copied locally the https://raw.githubusercontent.com/Azure/azure-k8s-metrics-adapter/master/deploy/adapter.yaml file and in the "kind: Deployment" record I replaced the empty "env:" section with the section below.
``` 
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: adapter-service-principal
                  key: azure-tenant-id
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: adapter-service-principal
                  key: azure-client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: adapter-service-principal
                  key: azure-client-secret
```
3. I deployed the adapter again `kubectl apply -f .\deploy-adapter.yaml` and verified that everything works so far `kubectl get all -n=custom-metrics`
4. I did the other 2 deployments, `kubectl apply -f .\externalmetric.yaml` and `kubectl apply -f .\hpa.yaml`.
5. I verified that it is working `kubectl  get --raw "/apis/external.metrics.k8s.io/v1beta
1/namespaces/default/queuemessages"`
