### ISSUE TITLE
Custom metrics sample needs to be updated

### ISSUE THREAD

**Issue by anujgeek** [Azure/azure-k8s-metrics-adapter#73]
**Describe the bug**
I wasn't able to get the custom metrics sample working. After some experimentation, I was able to figure out the way to use it.

Instead of deploying the custom metric:
```
kubectl apply -f deploy/custom-metric.yaml
```
We can now directly enter the metric in hpa yaml:
```
metrics:
- type: Pods
  pods:
    metric:
      name: performanceCounters-requestsPerSecond
    target:
      type: AverageValue
      averageValue: 10
```

You can also test out the api using:

```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/performanceCounters-requestsPerSecond"
```
