### ISSUE TITLE
Unable to get external metrics by raw query or via HPA

### ISSUE THREAD

**Issue by ankrause** [Azure/azure-k8s-metrics-adapter#79]
**Describe the bug**
Unable to get external metrics from API , either via an HPA or by raw query.

My HPAs are reporting that they are unable to get the external metric with the following error:

```
unable to get external metric {ns}/{metricName}/nil: unable to fetch metrics from external metrics API: Unknown Azure external metric client type provided:
```

Ultimately I traced this message to here: https://github.com/Azure/azure-k8s-metrics-adapter/blob/b8f3644ac05ace0beb867cd9c7feb643b3bd0b12/pkg/azure/externalmetrics/factory.go#L15

Which appears to be switching on the azMetricRequest.Type property sent from [here](https://github.com/Azure/azure-k8s-metrics-adapter/blob/8ddd042331852062802b784e0bb162a8955c90a0/pkg/provider/provider_external.go#L36). I didn't find where this property is set as it isn't in the [ParseAzureMetric](https://github.com/Azure/azure-k8s-metrics-adapter/blob/ef6a298f5ca63c522a0c134bc13a24143767997a/pkg/azure/externalmetrics/metricrequest.go#L30) method (from what I see).

That said, I decided to try adding a type property to my ExternalMetric resource definition like so:
```
apiVersion: azure.com/v1alpha2
kind: ExternalMetric
metadata:
  name: {name}
spec:
  type: Monitor
  azure:
    resourceGroup: {rg}
    resourceName: {rn}
    resourceProviderNamespace: Microsoft.ServiceBus
    resourceType: namespaces
  metric:
    aggregation: Total
    filter: EntityName eq '{entity}'
    metricName: ActiveMessages
```

after which I received this message instead (raw query used here):
```
Error from server (BadRequest): Unknown Azure external metric client type provided: Monitor
```

I didn't see this approach documented anywhere if that's the intended method of specifying client type.

**To Reproduce**
1. Deploy the latest custom metrics adapter by following the instructions with Azure AAD Pod Identity support.
2. Create an ExternalMetric for a Service Bus (see above definition).
3. Run a raw query against the metric, `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/{namespace}/{metricName}"`

**Expected behavior**
Metrics are returned both by raw query and to my HPA, allowing HPAs to autoscale off of both Azure Monitor and Azure Service Bus metrics.

**Kubernetes version (`kubectl version`):** 1.16.2
- [ ] Running on AKS

**Logs (`kubectl logs <metric adapter pod id>`)**

The metrics pod itself is working correctly in terms of the metrics themselves, from what I see:
```
I1116 14:41:49.590541       1 controller.go:134] succesfully proccessed item '{metricName}'
I1116 14:41:49.590586       1 controller.go:91] processing next item
I1116 14:41:49.590590       1 controller.go:98] processing item
```

I see no error messages in the pod log output.

**Comment by jsturtevant** [comment]
The use of Azure Monitor is documented in the [sample for queues](https://github.com/Azure/azure-k8s-metrics-adapter/blob/master/samples/servicebus-queue/deploy/externalmetric.yaml).  The value you found above is actually a [constant ](https://github.com/Azure/azure-k8s-metrics-adapter/blob/master/pkg/azure/externalmetrics/providers.go) for `azuremonitor`.  Does seem to need clearer documentation.  

An example external Metric using Azure Monitor would be:

```
apiVersion: azure.com/v1alpha2
kind: ExternalMetric
metadata:
  name: queuemessages
spec:
  type: azuremonitor
  azure:
    resourceGroup: sb-external-example
    resourceName: sb-external-ns
    resourceProviderNamespace: Microsoft.ServiceBus
    resourceType: namespaces
  metric:
    metricName: Messages
    aggregation: Total
    filter: EntityName eq 'externalq'
```

Another example is using App Gateway: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/scale-applications-using-appgw-metrics.md
