### ISSUE TITLE
Question about custom metrics for application insight

### ISSUE THREAD

**Issue by mrdotmoon** [Azure/azure-k8s-metrics-adapter#87]
We have multiple services running in k8s, and all of them report rps to application insight. Will hpa scale based on service's own rps?

**Comment by RomanDvorsky** [comment]
Hi, 
I would extend this question - it seems that you can use just one AppIsights per cluster? So all microservices hosted in the cluster have to log into the same AppInsights and you can differentiate service by using the `applicationID` in the customer metrics, right?

```
apiVersion: azure.com/v1alpha2
kind: CustomMetric
metadata:
  name: rps
spec:
  metric:
    metricName: performanceCounters/requestsPerSecond
    applicationID: <?micro service id?>
```

The issue we do have is that we have app insights per service therefore we do cannot use this solution, right?
