### ISSUE TITLE
External metric not working for Eventhubs

### ISSUE THREAD

**Issue by vishal8k** [Azure/azure-k8s-metrics-adapter#90]
**Describe the bug**
I've setup the metric adapter successfully and have established external metrics for services such as service bus, application gateway. But however When I tried to setup one for eventhub for the metric "IncomingMessages"  I was displayed with an error _"Error from server (ServiceUnavailable): the server is currently unable to handle the request"_

Below is my external metric YAML.

```
apiVersion: azure.com/v1alpha2
kind: ExternalMetric
metadata:
  name: myextmetric
  namespace: mynamespace
spec:
  type: azuremonitor
  azure:
    resourceGroup: myrg
    resourceName: evhubnamespacename
    resourceProviderNamespace: Microsoft.EventHub
    resourceType: namespaces
  metric:
    metricName: IncomingMessages
    aggregation: Total
    filter: EntityName eq 'customname'

```
